### ISSUE TITLE
Getting flake error: devshell attributes not provided

### ISSUE THREAD

**Issue by Narice** [srid/haskell-template#52] opened 2022-09-02 10:56 UTC
I'm getting:
```
error: flake 'git+file:///home/<user>/vault/dev/Current/haskell-template' does not provide attribute 'devShells.x86_64-linux.devShell.x86_64-linux', 'packages.x86_64-linux.devShell.x86_64-linux', 'legacyPackages.x86_64-linux.devShell.x86_64-linux', 'devShell.x86_64-linux' or 'defaultPackage.x86_64-linux
```
I just updated from nix 2.4 to 2.7 so I made sure to run nix develop:
```
$ nix develop
error: flake 'git+file:///home/narice/vault/dev/Current/haskell-template' does not provide attribute 'devShells.x86_64-linux.devShell.x86_64-linux', 'packages.x86_64-linux.devShell.x86_64-linux', 'legacyPackages.x86_64-linux.devShell.x86_64-linux', 'devShell.x86_64-linux' or 'defaultPackage.x86_64-linux
$ nix --version
nix (Nix) 2.7.0pre20220127_558c4ee
```
Maybe there was a change in the flake structure recently?

**Comment by srid** [comment] 2022-09-02 11:44
Duplicate of #46? Could you try 2.8 or later?

**Comment by srid** [comment] 2022-09-02 17:07
Let me know if the problem still appears after upgrading to 2.8!

**Closed by srid** 2022-09-02 17:07 UTC

**Comment by Narice** [comment] 2022-09-02 19:16
Oh I didn't comment, yes, sorry for the duplicate, it's possible that this is the issue, thank you!
